{% set version = "9.0.1" %}

package:
  name: framework7-cli
  version: {{ version }}

source:
  url: https://registry.npmjs.org/framework7-cli/-/framework7-cli-{{ version }}.tgz
  sha256: 5b04ab2d5f15a43062da8a0ebd51b27c5a69b42aff39f23061b98dd673734735

build:
  number: 1
  skip: true  # [win or ppc64le]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make
    - nodejs
    - pkg-config
    - pnpm
    - pnpm-licenses
    - python >={{ python_min }}
  host:
    - glib
    - libexpat
    - libvips
    - nodejs
  run:
    - nodejs

test:
  commands:
    - framework7 --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Framework7 command line utility (CLI)
  home: https://github.com/framework7io/framework7-cli
  dev_url: https://github.com/framework7io/framework7-cli

extra:
  recipe-maintainers:
    - danielnachun
